---
title       : Subsetting and sorting
subtitle    : 
author      : Jeffrey Leek 
job         : Johns Hopkins Bloomberg School of Public Health
logo        : bloomberg_shield.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow   # 
url:
  lib: ../../libraries
  assets: ../../assets
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---


```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F}
# make this an external chunk that can be included in any file
options(width = 100)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'fig/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
#hook1 <- function(x){ gsub("```\n*```r*\n*", "", x) }
#knit_hooks$set(document = hook1)
```

## Subsetting - quick review

```{r subsetting}
set.seed(13435)
X <- data.frame("var1"=sample(1:5),"var2"=sample(6:10),"var3"=sample(11:15)); X
# var1 var2 var3
1    2    8   15
2    3    7   12
3    5    6   14
4    1   10   11
5    4    9   13

X <- X[sample(1:5),]; X
# var1 var2 var3
1    2    8   15
4    1   10   11
2    3    7   12
3    5    6   14
5    4    9   13

X$var2[c(1,3)] = NA; X
# var1 var2 var3
1    2   NA   15
4    1   10   11
2    3   NA   12
3    5    6   14
5    4    9   13
```

## Subsetting - quick review

```{r ,dependson="subsetting"}

X[,1]
[1] 2 1 3 5 4

X[,"var1"]
[1] 2 1 3 5 4

X[1:2,"var2"]
[1] NA 10

```

## Logicals ands and ors

```{r ,dependson="subsetting"}

X[(X$var1 <= 3 & X$var3 > 11),]
# var1 var2 var3
1    2   NA   15
2    3   NA   12

X[(X$var1 <= 3 | X$var3 > 15),]
# var1 var2 var3
1    2   NA   15
4    1   10   11
2    3   NA   12

```

---

## Dealing with missing values

```{r ,dependson="subsetting"}

X[which(X$var2 > 8),]
# var1 var2 var3
4    1   10   11
5    4    9   13

```

---

## Sorting

```{r ,dependson="subsetting"}

sort(X$var1)
[1] 1 2 3 4 5

sort(X$var1,decreasing=TRUE)
[1] 5 4 3 2 1

sort(X$var2,na.last=TRUE)
[1]  6  9 10 NA NA

```

---

## Ordering

```{r ,dependson="subsetting"}

X[order(X$var1),]
# var1 var2 var3
4    1   10   11
1    2   NA   15
2    3   NA   12
5    4    9   13
3    5    6   14
```

## Ordering

```{r ,dependson="subsetting"}

X[order(X$var1,X$var3),]
# var1 var2 var3
4    1   10   11
1    2   NA   15
2    3   NA   12
5    4    9   13
3    5    6   14
```

## Ordering with plyr

```{r ,dependson="subsetting"}

library(plyr)
arrange(X,var1)
# var1 var2 var3
1    1   10   11
2    2   NA   15
3    3   NA   12
4    4    9   13
5    5    6   14

arrange(X,desc(var1))
# var1 var2 var3
1    5    6   14
2    4    9   13
3    3   NA   12
4    2   NA   15
5    1   10   11

```

## Adding rows and columns

```{r,dependson="subsetting"}

X$var4 <- rnorm(5); X
# var1 var2 var3       var4
1    2   NA   15  0.1875960
4    1   10   11  1.7869764
2    3   NA   12  0.4966936
3    5    6   14  0.0631830
5    4    9   13 -0.5361329
```

## Adding rows and columns

```{r,dependson="subsetting"}

Y <- cbind(X,rnorm(5)); Y
  var1 var2 var3       var4   rnorm(5)
1    2   NA   15  0.1875960  0.5439561
4    1   10   11  1.7869764  0.3304796
2    3   NA   12  0.4966936 -0.9710917
3    5    6   14  0.0631830 -0.9446847
5    4    9   13 -0.5361329 -0.2967423

```

---

## Notes and further resources

* R programming in the Data Science Track
* Andrew Jaffe's lecture notes [http://www.biostat.jhsph.edu/~ajaffe/lec_winterR/Lecture%202.pdf](http://www.biostat.jhsph.edu/~ajaffe/lec_winterR/Lecture%202.pdf)
